version: "3.6"
services:
  __CONST_SERVICE_NAME_POSTGRES:
    image: postgres:16
    restart: always
    volumes:
      - hasura_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  __CONST_SERVICE_NAME_HASURA:
    image: hasura/graphql-engine:latest
    ports:
      - "28085:8080"
    depends_on:
      - "__CONST_SERVICE_NAME_POSTGRES"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "${HASURA_GRAPHQL_METADATA_DATABASE_URL}"
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
      HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: true
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
      ACTION_BASE_URL: "${ACTION_BASE_URL}"
      HOOK_SECRET: "${HOOK_SECRET}"
      HOOK_SECRET_HEADER_NAME: "${HOOK_SECRET_HEADER_NAME}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  __CONST_SERVICE_NAME_HLAMBDA:
    image: hlambda/hlambda-core:latest
    environment:
      HLAMBDA_ADMIN_SECRET: "${HLAMBDA_ADMIN_SECRET}"
      HLAMBDA_JWT_PRIVATE_KEY: "${HLAMBDA_JWT_PRIVATE_KEY}"
      HASURA_GRAPHQL_API_ENDPOINT: "${HASURA_GRAPHQL_API_ENDPOINT}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HOOK_SECRET: "${HOOK_SECRET}"
      HOOK_SECRET_HEADER_NAME: "${HOOK_SECRET_HEADER_NAME}"
    ports:
      - "28086:1331"
    restart: always
    volumes:
      - hlambda_metadata:/usr/src/app/metadata
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  hasura_db_data:
  hlambda_metadata:

networks:
  default:
    external: true
    name: intranet
